// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: coordinator_sdfs_proto.proto

package process

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CoordinatorServiceForSDFSClient is the client API for CoordinatorServiceForSDFS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordinatorServiceForSDFSClient interface {
	PutFile(ctx context.Context, in *CoordinatorPutFileRequest, opts ...grpc.CallOption) (*CoordinatorPutFileReply, error)
}

type coordinatorServiceForSDFSClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorServiceForSDFSClient(cc grpc.ClientConnInterface) CoordinatorServiceForSDFSClient {
	return &coordinatorServiceForSDFSClient{cc}
}

func (c *coordinatorServiceForSDFSClient) PutFile(ctx context.Context, in *CoordinatorPutFileRequest, opts ...grpc.CallOption) (*CoordinatorPutFileReply, error) {
	out := new(CoordinatorPutFileReply)
	err := c.cc.Invoke(ctx, "/process.CoordinatorServiceForSDFS/PutFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorServiceForSDFSServer is the server API for CoordinatorServiceForSDFS service.
// All implementations must embed UnimplementedCoordinatorServiceForSDFSServer
// for forward compatibility
type CoordinatorServiceForSDFSServer interface {
	PutFile(context.Context, *CoordinatorPutFileRequest) (*CoordinatorPutFileReply, error)
	mustEmbedUnimplementedCoordinatorServiceForSDFSServer()
}

// UnimplementedCoordinatorServiceForSDFSServer must be embedded to have forward compatible implementations.
type UnimplementedCoordinatorServiceForSDFSServer struct {
}

func (UnimplementedCoordinatorServiceForSDFSServer) PutFile(context.Context, *CoordinatorPutFileRequest) (*CoordinatorPutFileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutFile not implemented")
}
func (UnimplementedCoordinatorServiceForSDFSServer) mustEmbedUnimplementedCoordinatorServiceForSDFSServer() {
}

// UnsafeCoordinatorServiceForSDFSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorServiceForSDFSServer will
// result in compilation errors.
type UnsafeCoordinatorServiceForSDFSServer interface {
	mustEmbedUnimplementedCoordinatorServiceForSDFSServer()
}

func RegisterCoordinatorServiceForSDFSServer(s grpc.ServiceRegistrar, srv CoordinatorServiceForSDFSServer) {
	s.RegisterService(&CoordinatorServiceForSDFS_ServiceDesc, srv)
}

func _CoordinatorServiceForSDFS_PutFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinatorPutFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceForSDFSServer).PutFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/process.CoordinatorServiceForSDFS/PutFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceForSDFSServer).PutFile(ctx, req.(*CoordinatorPutFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoordinatorServiceForSDFS_ServiceDesc is the grpc.ServiceDesc for CoordinatorServiceForSDFS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordinatorServiceForSDFS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "process.CoordinatorServiceForSDFS",
	HandlerType: (*CoordinatorServiceForSDFSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutFile",
			Handler:    _CoordinatorServiceForSDFS_PutFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coordinator_sdfs_proto.proto",
}
