// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: introducer.proto

package introducer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntroduceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip        string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port      int64  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Timestamp string `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *IntroduceRequest) Reset() {
	*x = IntroduceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_introducer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntroduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntroduceRequest) ProtoMessage() {}

func (x *IntroduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_introducer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntroduceRequest.ProtoReflect.Descriptor instead.
func (*IntroduceRequest) Descriptor() ([]byte, []int) {
	return file_introducer_proto_rawDescGZIP(), []int{0}
}

func (x *IntroduceRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IntroduceRequest) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *IntroduceRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type IntroduceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MembershipList []byte `protobuf:"bytes,1,opt,name=membershipList,proto3" json:"membershipList,omitempty"`
	Index          int64  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"` // index of the newly added node in the membershipList
	ProcessId      string `protobuf:"bytes,3,opt,name=processId,proto3" json:"processId,omitempty"`
}

func (x *IntroduceReply) Reset() {
	*x = IntroduceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_introducer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntroduceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntroduceReply) ProtoMessage() {}

func (x *IntroduceReply) ProtoReflect() protoreflect.Message {
	mi := &file_introducer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntroduceReply.ProtoReflect.Descriptor instead.
func (*IntroduceReply) Descriptor() ([]byte, []int) {
	return file_introducer_proto_rawDescGZIP(), []int{1}
}

func (x *IntroduceReply) GetMembershipList() []byte {
	if x != nil {
		return x.MembershipList
	}
	return nil
}

func (x *IntroduceReply) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *IntroduceReply) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

var File_introducer_proto protoreflect.FileDescriptor

var file_introducer_proto_rawDesc = []byte{
	0x0a, 0x10, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x22, 0x54,
	0x0a, 0x10, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x22, 0x6c, 0x0a, 0x0e, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x68, 0x69, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x49, 0x64, 0x32, 0x55, 0x0a, 0x0a, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72,
	0x12, 0x47, 0x0a, 0x09, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x12, 0x1c, 0x2e,
	0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x74, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x69, 0x6e,
	0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x63, 0x73, 0x34,
	0x32, 0x35, 0x2f, 0x6d, 0x70, 0x2f, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_introducer_proto_rawDescOnce sync.Once
	file_introducer_proto_rawDescData = file_introducer_proto_rawDesc
)

func file_introducer_proto_rawDescGZIP() []byte {
	file_introducer_proto_rawDescOnce.Do(func() {
		file_introducer_proto_rawDescData = protoimpl.X.CompressGZIP(file_introducer_proto_rawDescData)
	})
	return file_introducer_proto_rawDescData
}

var file_introducer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_introducer_proto_goTypes = []interface{}{
	(*IntroduceRequest)(nil), // 0: introducer.IntroduceRequest
	(*IntroduceReply)(nil),   // 1: introducer.IntroduceReply
}
var file_introducer_proto_depIdxs = []int32{
	0, // 0: introducer.Introducer.Introduce:input_type -> introducer.IntroduceRequest
	1, // 1: introducer.Introducer.Introduce:output_type -> introducer.IntroduceReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_introducer_proto_init() }
func file_introducer_proto_init() {
	if File_introducer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_introducer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntroduceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_introducer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntroduceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_introducer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_introducer_proto_goTypes,
		DependencyIndexes: file_introducer_proto_depIdxs,
		MessageInfos:      file_introducer_proto_msgTypes,
	}.Build()
	File_introducer_proto = out.File
	file_introducer_proto_rawDesc = nil
	file_introducer_proto_goTypes = nil
	file_introducer_proto_depIdxs = nil
}
